Prefix commands and builtins to prevent alias collisions

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,22 +6,22 @@ local config=${ZULU_CONFIG_DIR:-"${ZDOTDIR:-$HOME}/.config/zulu"}
 function _zulu_color() {
   local color=$1
 
-  shift
+  builtin shift
 
   case $color in
-    black)    echo "\033[0;30m${@}\033[0;m" ;;
-    red)      echo "\033[0;31m${@}\033[0;m" ;;
-    green)    echo "\033[0;32m${@}\033[0;m" ;;
-    yellow)   echo "\033[0;33m${@}\033[0;m" ;;
-    blue)     echo "\033[0;34m${@}\033[0;m" ;;
-    magenta)  echo "\033[0;35m${@}\033[0;m" ;;
-    cyan)     echo "\033[0;36m${@}\033[0;m" ;;
-    white)    echo "\033[0;37m${@}\033[0;m" ;;
+    black)    builtin echo "\033[0;30m${@}\033[0;m" ;;
+    red)      builtin echo "\033[0;31m${@}\033[0;m" ;;
+    green)    builtin echo "\033[0;32m${@}\033[0;m" ;;
+    yellow)   builtin echo "\033[0;33m${@}\033[0;m" ;;
+    blue)     builtin echo "\033[0;34m${@}\033[0;m" ;;
+    magenta)  builtin echo "\033[0;35m${@}\033[0;m" ;;
+    cyan)     builtin echo "\033[0;36m${@}\033[0;m" ;;
+    white)    builtin echo "\033[0;37m${@}\033[0;m" ;;
   esac
 }
 
 function _zulu_spinner_callback() {
-  print $@
+  builtin print $@
 }
 
 function _zulu_spinner_process() {
@@ -29,7 +29,7 @@ function _zulu_spinner_process() {
 
   while [[ 1 -eq 1 ]]; do
     _zulu_spinner_spin
-    sleep 0.1
+    command sleep 0.1
   done
 }
 
@@ -42,13 +42,13 @@ function _zulu_spinner_spin() {
   fi
 
   # Echo the frame
-  echo -n $frames[$spinner_index]
+  builtin echo -n $frames[$spinner_index]
 
   # Set the spinner index to the next frame
   spinner_index=$(( $(( $spinner_index + 1 )) % ${#frames} ))
 
   # Echo the message and return to the beginning of the line
-  echo -en " $msg\r"
+  builtin echo -en " $msg\r"
 }
 
 function _zulu_spinner_start() {
@@ -60,7 +60,7 @@ function _zulu_spinner_start() {
 
 function _zulu_spinner_stop() {
   [[ "$ZULU_SPINNER_PID" != "" ]] && kill "$ZULU_SPINNER_PID" > /dev/null
-  unset ZULU_SPINNER_PID
+  builtin unset ZULU_SPINNER_PID
 }
 
 
@@ -70,26 +70,26 @@ function _zulu_spinner_stop() {
 function _zulu_create_base() {
   local -a dirs; dirs=('bin' 'init' 'packages' 'share')
   for dir in "${dirs[@]}"; do
-    mkdir -p "$base/$dir"
-    touch "$base/$dir/.gitkeep"
+    command mkdir -p "$base/$dir"
+    command touch "$base/$dir/.gitkeep"
   done
 
-  mkdir -p "$config/functions"
-  touch "$config/packages"
+  command mkdir -p "$config/functions"
+  command touch "$config/packages"
 }
 
 ###
 # Install the zulu core functions
 ###
 function _zulu_install_core() {
-  git clone "https://github.com/zulu-zsh/zulu" "$base/core"
+  command git clone "https://github.com/zulu-zsh/zulu" "$base/core"
 }
 
 ###
 # Install the package index
 ###
 function _zulu_install_index() {
-  git clone "https://github.com/zulu-zsh/index" "$base/index"
+  command git clone "https://github.com/zulu-zsh/index" "$base/index"
 }
 
 ###
@@ -110,9 +110,9 @@ function _zulu_create_path() {
   separator=$'\n'
   local oldIFS=$IFS
   IFS="$separator"; out="${items[*]/#/${separator}}"
-  echo ${out:${#separator}} >! $pathfile
+  builtin echo ${out:${#separator}} >! $pathfile
   IFS=$oldIFS
-  unset oldIFS
+  builtin unset oldIFS
 }
 
 ###
@@ -133,9 +133,9 @@ function _zulu_create_fpath() {
   separator=$'\n'
   local oldIFS=$IFS
   IFS="$separator"; out="${items[*]/#/${separator}}"
-  echo ${out:${#separator}} >! $fpathfile
+  builtin echo ${out:${#separator}} >! $fpathfile
   IFS=$oldIFS
-  unset oldIFS
+  builtin unset oldIFS
 }
 
 ###
@@ -155,9 +155,9 @@ function _zulu_create_cdpath() {
   separator=$'\n'
   local oldIFS=$IFS
   IFS="$separator"; out="${items[*]/#/${separator}}"
-  echo ${out:${#separator}} >! $cdpathfile
+  builtin echo ${out:${#separator}} >! $cdpathfile
   IFS=$oldIFS
-  unset oldIFS
+  builtin unset oldIFS
 }
 
 ###
@@ -165,20 +165,20 @@ function _zulu_create_cdpath() {
 ###
 function _zulu_create_aliases() {
   local aliasfile="$config/alias"
-  echo "" > $aliasfile
+  builtin echo "" > $aliasfile
   local oldIFS=$IFS
   IFS=$'\n'; for a in `alias`; do
-    echo "alias $a\n" >> $aliasfile
+    builtin echo "alias $a\n" >> $aliasfile
   done
   IFS=$oldIFS
-  unset oldIFS
+  builtin unset oldIFS
 }
 
 ###
 # Install the zulu completion definitions
 ###
 function _zulu_install_completion() {
-  ln -s "$base/core/zulu.zsh-completion" "$base/share/_zulu"
+  command ln -s "$base/core/zulu.zsh-completion" "$base/share/_zulu"
 }
 
 ###
@@ -189,7 +189,7 @@ function _zulu_install_init() {
   if [[ -e "${ZDOTDIR:-$HOME}/.zshrc" ]]; then
     # If it contains the command 'zulu init', we don't need to
     # add the initialisation script again
-    local check_script=$(cat "${ZDOTDIR:-$HOME}/.zshrc" | grep -E -e '^zulu init')
+    local check_script=$(command cat "${ZDOTDIR:-$HOME}/.zshrc" | command grep -E -e '^zulu init')
     if [[ -n "$check_script" ]]; then
       return 0
     fi
@@ -202,7 +202,7 @@ source "${ZULU_DIR:-"${ZDOTDIR:-$HOME}/.zulu"}/core/zulu"
 zulu init
 '
 
-  echo "$init" >> "${ZDOTDIR:-$HOME}/.zshrc"
+  builtin echo "$init" >> "${ZDOTDIR:-$HOME}/.zshrc"
 }
 
 ###
@@ -212,14 +212,14 @@ function _zulu_install_cleanup_on_failure() {
   _zulu_spinner_start "Rolling back installation..."
 
   if [[ -d $base ]]; then
-    rm -rf $base
+    command rm -rf $base
   fi
 
   if [[ -d $config && $config_exists -eq 0 ]]; then
-    rm -rf $config
+    command rm -rf $config
   fi
 
-  echo "$(_zulu_color green '✔') Installation rolled back successfully        "
+  builtin echo "$(_zulu_color green '✔') Installation rolled back successfully        "
   _zulu_spinner_stop
 }
 
@@ -230,15 +230,15 @@ function zulu_install() {
   local out config_exists=0 overwrite_config=0
 
   if [[ -d $base ]]; then
-    echo $(_zulu_color red "Zulu is already installed at $base.")
-    echo "If you are wishing to update zulu, you should run 'zulu self-update' instead."
+    builtin echo $(_zulu_color red "Zulu is already installed at $base.")
+    builtin echo "If you are wishing to update zulu, you should run 'zulu self-update' instead."
     return 1
   fi
 
   if [[ -d $config ]]; then
     config_exists=1
-    echo $(_zulu_color yellow "Config already exists at $config. Overwrite? [y|N]")
-    read -rs -k 1 input
+    builtin echo $(_zulu_color yellow "Config already exists at $config. Overwrite? [y|N]")
+    builtin read -rs -k 1 input
 
     case $input in
       y)
@@ -255,13 +255,13 @@ function zulu_install() {
 
   if [ $? -eq 0 ]; then
     _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Created directory structure        "
+    builtin echo "$(_zulu_color green '✔') Created directory structure        "
   else
     _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error creating directory structure        "
-    echo "$out"
+    builtin echo "$(_zulu_color red '✘') Error creating directory structure        "
+    builtin echo "$out"
     _zulu_install_cleanup_on_failure
-    exit 1
+    builtin exit 1
   fi
 
   _zulu_spinner_start "Installing zulu core..."
@@ -269,13 +269,13 @@ function zulu_install() {
 
   if [ $? -eq 0 ]; then
     _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Installed zulu core        "
+    builtin echo "$(_zulu_color green '✔') Installed zulu core        "
   else
     _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error installing zulu core        "
-    echo "$out"
+    builtin echo "$(_zulu_color red '✘') Error installing zulu core        "
+    builtin echo "$out"
     _zulu_install_cleanup_on_failure
-    exit 1
+    builtin exit 1
   fi
 
   _zulu_spinner_start "Installing package index..."
@@ -283,13 +283,13 @@ function zulu_install() {
 
   if [ $? -eq 0 ]; then
     _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Installed package index        "
+    builtin echo "$(_zulu_color green '✔') Installed package index        "
   else
     _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error installing package index        "
-    echo "$out"
+    builtin echo "$(_zulu_color red '✘') Error installing package index        "
+    builtin echo "$out"
     _zulu_install_cleanup_on_failure
-    exit 1
+    builtin exit 1
   fi
 
   if [[ $config_exists -eq 0 ]] || [[ $config_exists -eq 1 && $overwrite_config -eq 1 ]]; then
@@ -298,13 +298,13 @@ function zulu_install() {
 
     if [ $? -eq 0 ]; then
       _zulu_spinner_stop
-      echo "$(_zulu_color green '✔') Initialized \$PATH        "
+      builtin echo "$(_zulu_color green '✔') Initialized \$PATH        "
     else
       _zulu_spinner_stop
-      echo "$(_zulu_color red '✘') Error initializing \$PATH        "
-      echo "$out"
+      builtin echo "$(_zulu_color red '✘') Error initializing \$PATH        "
+      builtin echo "$out"
       _zulu_install_cleanup_on_failure
-      exit 1
+      builtin exit 1
     fi
 
     _zulu_spinner_start "Initializing \$fpath..."
@@ -312,13 +312,13 @@ function zulu_install() {
 
     if [ $? -eq 0 ]; then
       _zulu_spinner_stop
-      echo "$(_zulu_color green '✔') Initialized \$fpath        "
+      builtin echo "$(_zulu_color green '✔') Initialized \$fpath        "
     else
       _zulu_spinner_stop
-      echo "$(_zulu_color red '✘') Error initializing \$fpath        "
-      echo "$out"
+      builtin echo "$(_zulu_color red '✘') Error initializing \$fpath        "
+      builtin echo "$out"
       _zulu_install_cleanup_on_failure
-      exit 1
+      builtin exit 1
     fi
 
     _zulu_spinner_start "Initializing \$cdpath..."
@@ -326,13 +326,13 @@ function zulu_install() {
 
     if [ $? -eq 0 ]; then
       _zulu_spinner_stop
-      echo "$(_zulu_color green '✔') Initialized \$cdpath        "
+      builtin echo "$(_zulu_color green '✔') Initialized \$cdpath        "
     else
       _zulu_spinner_stop
-      echo "$(_zulu_color red '✘') Error initializing \$cdpath        "
-      echo "$out"
+      builtin echo "$(_zulu_color red '✘') Error initializing \$cdpath        "
+      builtin echo "$out"
       _zulu_install_cleanup_on_failure
-      exit 1
+      builtin exit 1
     fi
 
     _zulu_spinner_start "Initializing aliases..."
@@ -340,13 +340,13 @@ function zulu_install() {
 
     if [ $? -eq 0 ]; then
       _zulu_spinner_stop
-      echo "$(_zulu_color green '✔') Initialized aliases        "
+      builtin echo "$(_zulu_color green '✔') Initialized aliases        "
     else
       _zulu_spinner_stop
-      echo "$(_zulu_color red '✘') Error initializing aliases        "
-      echo "$out"
+      builtin echo "$(_zulu_color red '✘') Error initializing aliases        "
+      builtin echo "$out"
       _zulu_install_cleanup_on_failure
-      exit 1
+      builtin exit 1
     fi
 
     _zulu_spinner_start "Installing completion..."
@@ -354,13 +354,13 @@ function zulu_install() {
 
     if [ $? -eq 0 ]; then
       _zulu_spinner_stop
-      echo "$(_zulu_color green '✔') Installed completion        "
+      builtin echo "$(_zulu_color green '✔') Installed completion        "
     else
       _zulu_spinner_stop
-      echo "$(_zulu_color red '✘') Error installing completion        "
-      echo "$out"
+      builtin echo "$(_zulu_color red '✘') Error installing completion        "
+      builtin echo "$out"
       _zulu_install_cleanup_on_failure
-      exit 1
+      builtin exit 1
     fi
   fi
 
@@ -369,58 +369,58 @@ function zulu_install() {
 
   if [ $? -eq 0 ]; then
     _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Installed initialization script        "
+    builtin echo "$(_zulu_color green '✔') Installed initialization script        "
   else
     _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error installing initialization script        "
-    echo "$out"
+    builtin echo "$(_zulu_color red '✘') Error installing initialization script        "
+    builtin echo "$out"
     _zulu_install_cleanup_on_failure
-    exit 1
+    builtin exit 1
   fi
 
   local oldPWD=$PWD
-  cd "$base/core"
+  builtin cd "$base/core"
   _zulu_spinner_start "Running build script..."
   out=$(./build.zsh 2>&1)
   state=$?
 
-  cd $oldPWD
-  unset oldPWD
+  builtin cd $oldPWD
+  builtin unset oldPWD
 
   if [ $state -eq 0 ]; then
     _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Build script complete        "
+    builtin echo "$(_zulu_color green '✔') Build script complete        "
   else
     _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error running build script        "
-    echo "$out"
+    builtin echo "$(_zulu_color red '✘') Error running build script        "
+    builtin echo "$out"
     _zulu_install_cleanup_on_failure
-    exit 1
+    builtin exit 1
   fi
 
   # Source zulu and install dependencies
-  source "$base/core/zulu"
+  builtin source "$base/core/zulu"
   zulu init
 
   # Install some important packages
   zulu install color revolver zulu-theme
   zulu theme zulu-theme
 
-  echo
-  echo " _____         ___"
-  echo "/__  /  __  __/  /_  __"
-  echo "  / /  / / / /  / / / /"
-  echo " / /__/ /_/ /  / /_/ /"
-  echo "/____/\\____/__/\\____/"
-  echo
-  echo "Version $(zulu --version)"
-  echo
-  echo "Thanks for installing Zulu! You're now all set up and ready to go."
-  echo
-  echo "Documentation: https://zulu.sh/docs"
-  echo "Feedback:      https://github.com/zulu-zsh/zulu/issues"
-  echo "Community:     https://gitter.im/zulu-zsh/zulu"
-  echo
+  builtin echo
+  builtin echo " _____         ___"
+  builtin echo "/__  /  __  __/  /_  __"
+  builtin echo "  / /  / / / /  / / / /"
+  builtin echo " / /__/ /_/ /  / /_/ /"
+  builtin echo "/____/\\____/__/\\____/"
+  builtin echo
+  builtin echo "Version $(zulu --version)"
+  builtin echo
+  builtin echo "Thanks for installing Zulu! You're now all set up and ready to go."
+  builtin echo
+  builtin echo "Documentation: https://zulu.sh/docs"
+  builtin echo "Feedback:      https://github.com/zulu-zsh/zulu/issues"
+  builtin echo "Community:     https://gitter.im/zulu-zsh/zulu"
+  builtin echo
 }
 
 zulu_install
