Check for existing zulu installation when installing Script will exit if the zulu base directory is found.
If the zulu config directory is found, the user is prompted whether or not to
overwrite the existing config. If they choose no, zulu will continue the install
leaving the existing config intact. This is handy if the config dir is synced
between computers.

Also runs zulu bundle at the end of the install, so that if a packagefile is
found all packages within it are installed and available immediately as part
of the install.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -146,6 +146,16 @@ function _zulu_install_completion() {
 # Install the initialization script
 ###
 function _zulu_install_init() {
+  # Check if a .zshrc already exists
+  if [[ -e "${ZDOTDIR:-$HOME}/.zshrc" ]]; then
+    # If it contains the command 'zulu init', we don't need to
+    # add the initialisation script again
+    local check_script=$(cat "${ZDOTDIR:-$HOME}/.zshrc" | grep 'zulu init')
+    if [[ $? -eq 0 ]]; then
+      return 0
+    fi
+  fi
+
   # Add the init script to .zshrc
   local init='
 # Initialise zulu plugin manager
@@ -161,15 +171,15 @@ zulu init
 ###
 function _zulu_install_cleanup_on_failure() {
   _zulu_spinner_start "Rolling back installation..."
-  
+
   if [[ -d $base ]]; then
     rm -rf $base
   fi
-  
-  if [[ -d $config ]]; then
+
+  if [[ -d $config && $config_exists -eq 0 ]]; then
     rm -rf $config
   fi
-  
+
   echo "$(_zulu_color green '✔') Installation rolled back successfully        "
   _zulu_spinner_stopped
 }
@@ -178,6 +188,29 @@ function _zulu_install_cleanup_on_failure() {
 # Install the zulu framework
 ###
 function zulu_install() {
+  local out config_exists=0 overwrite_config=0
+
+  if [[ -d $base ]]; then
+    echo $(_zulu_color red "Zulu is already installed at $base.")
+    echo "If you are wishing to update zulu, you should run 'zulu self-update' instead."
+    return 1
+  fi
+
+  if [[ -d $config ]]; then
+    config_exists=1
+    echo $(_zulu_color yellow "Config already exists at $config. Overwrite? [y|N]")
+    read -rs -k 1 input
+
+    case $input in
+      y)
+        overwrite_config=1
+        ;;
+      *)
+        overwrite_config=0
+        ;;
+    esac
+  fi
+
   _zulu_spinner_start "Creating directory structure..."
   out=$(_zulu_create_base 2>&1)
 
@@ -220,74 +253,76 @@ function zulu_install() {
     exit 1
   fi
 
-  _zulu_spinner_start "Initializing \$PATH..."
-  out=$(_zulu_create_path 2>&1)
+  if [[ $config_exists -eq 0 ]] || [[ $config_exists -eq 1 && $overwrite_config -eq 1 ]]; then
+    _zulu_spinner_start "Initializing \$PATH..."
+    out=$(_zulu_create_path 2>&1)
 
-  if [ $? -eq 0 ]; then
-    _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Initialized \$PATH        "
-  else
-    _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error initializing \$PATH        "
-    echo "$out"
-    _zulu_install_cleanup_on_failure
-    exit 1
-  fi
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(_zulu_color green '✔') Initialized \$PATH        "
+    else
+      _zulu_spinner_stop
+      echo "$(_zulu_color red '✘') Error initializing \$PATH        "
+      echo "$out"
+      _zulu_install_cleanup_on_failure
+      exit 1
+    fi
 
-  _zulu_spinner_start "Initializing \$fpath..."
-  out=$(_zulu_create_fpath 2>&1)
+    _zulu_spinner_start "Initializing \$fpath..."
+    out=$(_zulu_create_fpath 2>&1)
 
-  if [ $? -eq 0 ]; then
-    _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Initialized \$fpath        "
-  else
-    _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error initializing \$fpath        "
-    echo "$out"
-    _zulu_install_cleanup_on_failure
-    exit 1
-  fi
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(_zulu_color green '✔') Initialized \$fpath        "
+    else
+      _zulu_spinner_stop
+      echo "$(_zulu_color red '✘') Error initializing \$fpath        "
+      echo "$out"
+      _zulu_install_cleanup_on_failure
+      exit 1
+    fi
 
-  _zulu_spinner_start "Initializing \$cdpath..."
-  out=$(_zulu_create_cdpath 2>&1)
+    _zulu_spinner_start "Initializing \$cdpath..."
+    out=$(_zulu_create_cdpath 2>&1)
 
-  if [ $? -eq 0 ]; then
-    _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Initialized \$cdpath        "
-  else
-    _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error initializing \$cdpath        "
-    echo "$out"
-    _zulu_install_cleanup_on_failure
-    exit 1
-  fi
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(_zulu_color green '✔') Initialized \$cdpath        "
+    else
+      _zulu_spinner_stop
+      echo "$(_zulu_color red '✘') Error initializing \$cdpath        "
+      echo "$out"
+      _zulu_install_cleanup_on_failure
+      exit 1
+    fi
 
-  _zulu_spinner_start "Initializing aliases..."
-  out=$(_zulu_create_aliases 2>&1)
+    _zulu_spinner_start "Initializing aliases..."
+    out=$(_zulu_create_aliases 2>&1)
 
-  if [ $? -eq 0 ]; then
-    _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Initialized aliases        "
-  else
-    _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error initializing aliases        "
-    echo "$out"
-    _zulu_install_cleanup_on_failure
-    exit 1
-  fi
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(_zulu_color green '✔') Initialized aliases        "
+    else
+      _zulu_spinner_stop
+      echo "$(_zulu_color red '✘') Error initializing aliases        "
+      echo "$out"
+      _zulu_install_cleanup_on_failure
+      exit 1
+    fi
 
-  _zulu_spinner_start "Installing completion..."
-  out=$(_zulu_install_completion 2>&1)
+    _zulu_spinner_start "Installing completion..."
+    out=$(_zulu_install_completion 2>&1)
 
-  if [ $? -eq 0 ]; then
-    _zulu_spinner_stop
-    echo "$(_zulu_color green '✔') Installed completion        "
-  else
-    _zulu_spinner_stop
-    echo "$(_zulu_color red '✘') Error installing completion        "
-    echo "$out"
-    _zulu_install_cleanup_on_failure
-    exit 1
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(_zulu_color green '✔') Installed completion        "
+    else
+      _zulu_spinner_stop
+      echo "$(_zulu_color red '✘') Error installing completion        "
+      echo "$out"
+      _zulu_install_cleanup_on_failure
+      exit 1
+    fi
   fi
 
   _zulu_spinner_start "Installing initialization script..."
@@ -307,6 +342,7 @@ function zulu_install() {
   # Source zulu and install dependencies
   source "$base/core/zulu"
   zulu init
+  zulu bundle
 }
 
 zulu_install
